/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const MachinePart = IDL.Variant({
  'chillerUnit' : IDL.Null,
  'mistUnit' : IDL.Null,
  'coolantFiltrationUnit' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Contact = IDL.Record({
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Machine = IDL.Record({
  'id' : IDL.Text,
  'lastCleaningDone' : Time,
  'name' : IDL.Text,
  'nextDue' : Time,
  'machineNo' : IDL.Opt(IDL.Text),
  'machinePart' : MachinePart,
});
export const LogEntry = IDL.Record({
  'userId' : IDL.Vec(IDL.Nat8),
  'timestamp' : Time,
  'eventType' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMachine' : IDL.Func(
      [IDL.Text, IDL.Text, Time, Time, IDL.Opt(IDL.Text), MachinePart],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMachine' : IDL.Func([IDL.Text], [], []),
  'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getAllMachines' : IDL.Func([], [IDL.Vec(Machine)], ['query']),
  'getAuditLogs' : IDL.Func([], [IDL.Vec(LogEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMachine' : IDL.Func([IDL.Text], [Machine], ['query']),
  'getMachinesByName' : IDL.Func([IDL.Text], [IDL.Vec(Machine)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logEvent' : IDL.Func([IDL.Vec(IDL.Nat8), IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateMachine' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(Time),
        IDL.Opt(Time),
        IDL.Opt(IDL.Text),
        IDL.Opt(MachinePart),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const MachinePart = IDL.Variant({
    'chillerUnit' : IDL.Null,
    'mistUnit' : IDL.Null,
    'coolantFiltrationUnit' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Contact = IDL.Record({
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Machine = IDL.Record({
    'id' : IDL.Text,
    'lastCleaningDone' : Time,
    'name' : IDL.Text,
    'nextDue' : Time,
    'machineNo' : IDL.Opt(IDL.Text),
    'machinePart' : MachinePart,
  });
  const LogEntry = IDL.Record({
    'userId' : IDL.Vec(IDL.Nat8),
    'timestamp' : Time,
    'eventType' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMachine' : IDL.Func(
        [IDL.Text, IDL.Text, Time, Time, IDL.Opt(IDL.Text), MachinePart],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMachine' : IDL.Func([IDL.Text], [], []),
    'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getAllMachines' : IDL.Func([], [IDL.Vec(Machine)], ['query']),
    'getAuditLogs' : IDL.Func([], [IDL.Vec(LogEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMachine' : IDL.Func([IDL.Text], [Machine], ['query']),
    'getMachinesByName' : IDL.Func([IDL.Text], [IDL.Vec(Machine)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logEvent' : IDL.Func([IDL.Vec(IDL.Nat8), IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateMachine' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(Time),
          IDL.Opt(Time),
          IDL.Opt(IDL.Text),
          IDL.Opt(MachinePart),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };